name: Build & Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_and_release:
    name: Build packages and release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD_MAIN: pyinstaller -F -w --icon=icon.png --add-data "icon.png;." --version-file=version.txt -n OnionSavesBackup-win64 main.py
            CMD_BUILD_UPDATER: pyinstaller -F -n updater -i icon.png updater.py
            OUT_FILE_NAME_MAIN: OnionSavesBackup-win64.exe
            OUT_FILE_NAME_UPDATER: updater.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.7 <3.13"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build main executable with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD_MAIN}}
      - name: Build updater executable with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD_UPDATER}}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          prerelease: false
          files: |
            dist/${{matrix.OUT_FILE_NAME_MAIN}}
            dist/${{matrix.OUT_FILE_NAME_UPDATER}}

permissions:
  contents: write